// GENERATED FILE — do not edit; refresh with `pnpm update-url-rules`.
//
// Tracking-parameter ruleset vendored from @protontech/tidy-url@1.18.5 (data/rules.js),
// Proton's maintained fork of https://github.com/DrKain/tidy-url.
// Upstream license: MIT — Copyright (c) 2021 DrKain (https://github.com/DrKain)
//
// Carried fields: the host matcher (match/flags; tested against the URL host,
// or the full href when matchHref), the param names to strip (rules), params
// protected from any rule (allow), and URL patterns that opt a URL out of the
// provider (exclude). Upstream's redirect/AMP/decode features are out of scope;
// 56 providers that only did those were dropped (176 kept).
// Generated 2026-07-13.

export interface TrackingProvider {
	name: string;
	/** Host-matcher regex source; tested against the URL host (href when matchHref). */
	match: string;
	flags: string;
	matchHref?: boolean;
	/** Param names to strip (compared lowercased). */
	rules: readonly string[];
	/** Param names protected from ANY rule on this provider's URLs. */
	allow?: readonly string[];
	/** URL patterns that opt a URL out of this provider entirely. */
	exclude?: readonly { match: string; flags: string }[];
}

export const TIDY_VERSION = "1.18.5";

export const TIDY_RULES: readonly TrackingProvider[] = [
	{"name":"Global","match":".*","flags":"","rules":["utm_source","utm_medium","utm_term","utm_campaign","utm_content","utm_name","utm_cid","utm_reader","utm_viz_id","utm_pubreferrer","utm_swu","utm_social-type","utm_brand","utm_team","utm_feeditemid","utm_id","utm_marketing_tactic","utm_creative_format","utm_campaign_id","utm_source_platform","utm_timestamp","utm_souce","utm_couponvalue","itm_source","itm_medium","itm_term","itm_campaign","itm_content","itm_channel","itm_source_s","itm_medium_s","itm_campaign_s","itm_audience","int_source","int_cmp_name","int_cmp_id","int_cmp_creative","int_medium","int_campaign","int_content","pk_campaign","pk_cpn","pk_source","pk_medium","pk_keyword","pk_kwd","pk_content","pk_cid","piwik_campaign","piwik_cpn","piwik_source","piwik_medium","piwik_keyword","piwik_kwd","piwik_content","piwik_cid","gclid","ga_source","ga_medium","ga_term","ga_content","ga_campaign","ga_place","gclid","gclsrc","hsa_cam","hsa_grp","hsa_mt","hsa_src","hsa_ad","hsa_acc","hsa_net","hsa_kw","hsa_tgt","hsa_ver","hsa_la","hsa_ol","fbclid","oly_enc_id","oly_anon_id","vero_id","vero_conv","__s","_hsenc","_hsmi","__hssc","__hstc","__hsfp","hsCtaTracking","mkt_tok","mtm_campaign","mtm_keyword","mtm_kwd","mtm_source","mtm_medium","mtm_content","mtm_cid","mtm_group","mtm_placement","elqTrackId","elq","elqak","elqaid","elqat","elqCampaignId","elqTrack","mc_cid","mc_eid","ncid","cmpid","mbid","rdt_cid"]},
	{"name":"audible.com","match":"www.audible.com","flags":"i","rules":["qid","sr","pf_rd_p","pf_rd_r","plink","ref"]},
	{"name":"bandcamp.com","match":".*.bandcamp.com","flags":"i","rules":["from","search_item_id","search_item_type","search_match_part","search_page_id","search_page_no","search_rank","search_sig"]},
	{"name":"amazon.com","match":"amazon\\.[a-z0-9]{0,3}","flags":"i","rules":["psc","colid","coliid","linkId","tag","linkCode","ms3_c","pf_rd_s","pf_rd_t"," pf_rd_i","pf_rd_m","pd_rd_w","qid","sr","keywords","dchild","ref","ref_","rnid","pf_rd_r","pf_rd_p","pd_rd_r","smid","pd_rd_wg","content-id","spLa","crid","sprefix","hvlocint","hvdvcmdl","hvptwo","hvpone","hvpos","qu","pd_rd_i","nc2","nc1","trk","sc_icampaign","trkCampaign","ufe","sc_icontent","sc_ichannel","sc_iplace","sc_country","sc_outcome","sc_geo","sc_campaign","sc_channel"]},
	{"name":"reddit.com","match":".*.reddit.com","flags":"i","rules":["ref_campaign","ref_source","tags","keyword","channel","campaign","user_agent","domain","base_url","$android_deeplink_path","$deeplink_path","$og_redirect","share_id","correlation_id","ref","rdt"]},
	{"name":"app.link","match":".*\\.app\\.link","flags":"i","rules":["tags","keyword","channel","campaign","user_agent","domain","base_url","$android_deeplink_path","$deeplink_path","$og_redirect","compact_view","dnt","adblock","geoip_country","referrer_domain","referrer_url"]},
	{"name":"twitch.tv","match":"www.twitch.tv","flags":"i","rules":["tt_medium","tt_content","tt_email_id"]},
	{"name":"blog.twitch.tv","match":"blog.twitch.tv","flags":"i","rules":["utm_referrer"]},
	{"name":"pixiv.net","match":"www.pixiv.net","flags":"i","rules":["p","i","g"]},
	{"name":"spotify.com","match":"open.spotify.com","flags":"i","rules":["si","utm_source","context","sp_cid","_branch_match_id","_branch_referrer"],"allow":["go","nd"]},
	{"name":"aliexpress.com","match":"^(?:https?:\\/\\/)?(?:[^.]+\\.)?aliexpress\\.(?:[a-z]{2,}){1,}","flags":"i","rules":["_t","spm","algo_pvid","algo_expid","btsid","ws_ab_test","initiative_id","origin","widgetId","tabType","productId","productIds","gps-id","scm","scm_id","scm-url","pvid","algo_exp_id","pdp_pi","fromRankId","sourceType","utparam","gatewayAdapt","_evo_buckets","tpp_rcmd_bucket_id","scenario","pdp_npi","tt","spreadType","srcSns","bizType","social_params","aff_fcid","aff_fsk","aff_platform","aff_trace_key","shareId","platform","businessType","terminal_id","afSmartRedirect","sk","gbraid"],"allow":["sku_id","pdp_ext_f"]},
	{"name":"google.com","match":"www.google\\..*","flags":"i","rules":["sourceid","client","aqs","sxsrf","uact","ved","iflsig","source","ei","oq","gs_lcp","sclient","bih","biw","sa","dpr","rlz","gs_lp","sca_esv","si","gs_l","gs_lcrp"]},
	{"name":"youtube.com","match":".*.youtube.com","flags":"i","rules":["gclid","feature","app","src","lId","cId","embeds_referring_euri"]},
	{"name":"humblebundle.com","match":"www.humblebundle.com","flags":"i","rules":["hmb_source","hmb_medium","hmb_campaign","mcID","linkID"],"allow":["partner"]},
	{"name":"greenmangaming.com","match":"www.greenmangaming.com","flags":"i","rules":["CJEVENT","cjevent","irclickid","irgwc","pdpgatetoken"]},
	{"name":"fanatical.com","match":"www.fanatical.com","flags":"i","rules":["cj_pid","cj_aid","aff_track","CJEVENT","cjevent"]},
	{"name":"newsweek.com","match":"www.newsweek.com","flags":"i","rules":["subref","amp"]},
	{"name":"imgur.com","match":"imgur.com","flags":"i","rules":["source"]},
	{"name":"plex.tv","match":".*.plex.tv","flags":"i","rules":["origin","plex_utm","sl","ckhid"]},
	{"name":"imdb.com","match":"^.*\\.imdb\\.com","flags":"i","rules":["ref_","ref\\_","pf_rd_m","pf_rd_r","pf_rd_p","pf_rd_s","pf_rd_t","pf_rd_i","ref_hp_hp_e_2","rf","ref"]},
	{"name":"gog.com","match":"www.gog.com","flags":"i","rules":["at_gd","rec_scenario_id","rec_sub_source_id","rec_item_id","vds_id","prod_id","rec_source"]},
	{"name":"tiktok.com","match":"www.tiktok.com","flags":"i","rules":["is_copy_url","is_from_webapp","sender_device","sender_web_id","sec_user_id","share_app_id","share_item_id","share_link_id","social_sharing","_r","source","user_id","u_code","tt_from","share_author_id","sec_uid","checksum","_d","refer","enter_from","enter_method","attr_medium","attr_source"],"allow":["lang"]},
	{"name":"facebook.com","match":".*.facebook.com","flags":"i","rules":["fbclid","fb_ref","fb_source","referral_code","referral_story_type","tracking","ref"],"exclude":[{"match":"www\\.facebook\\.com\\/sharer","flags":"i"}]},
	{"name":"yandex.com","match":"yandex.com","flags":"i","rules":["lr","from","grhow","origin","_openstat"]},
	{"name":"store.steampowered.com","match":"store.steampowered.com","flags":"i","rules":["snr"]},
	{"name":"findojobs.co.nz","match":"www.findojobs.co.nz","flags":"i","rules":["source"]},
	{"name":"linkedin.com","match":".*.linkedin.com","flags":"i","rules":["contextUrn","destRedirectURL","lipi","licu","trk","trkInfo","originalReferer","upsellOrderOrigin","upsellTrk","upsellTrackingId","src","trackingId","midToken","midSig","trkEmail","eid"],"allow":["otpToken"]},
	{"name":"indeed.com","match":".*.indeed.com","flags":"i","rules":["from","attributionid"]},
	{"name":"discord.com","match":"(?:.*\\.)?discord\\.com","flags":"i","rules":["source","ref"]},
	{"name":"medium.com","match":"medium.com","flags":"i","rules":["source"]},
	{"name":"twitter.com","match":"twitter.com","flags":"i","rules":["s","src","ref_url","ref_src"]},
	{"name":"voidu.com","match":"voidu.com","flags":"i","rules":["affiliate"]},
	{"name":"wingamestore.com","match":"wingamestore.com","flags":"i","rules":["ars"]},
	{"name":"gamebillet.com","match":"gamebillet.com","flags":"i","rules":["affiliate"]},
	{"name":"gamesload.com","match":"^www.gamesload.com","flags":"i","rules":["affil"],"allow":["REF"]},
	{"name":"mightyape","match":"mightyape.(co.nz|com.au)","flags":"i","rules":["m"]},
	{"name":"apple.com","match":".*.apple.com","flags":"i","rules":["uo","app","at","ct","ls","pt","mt","itsct","itscg","referrer","src","cid"]},
	{"name":"music.apple.com","match":"music.apple.com","flags":"i","rules":["i","lId","cId","sr","src"]},
	{"name":"play.google.com","match":"play.google.com","flags":"i","rules":["referrer","pcampaignid"]},
	{"name":"lenovo.com","match":".*.lenovo.com","flags":"i","rules":["PID","clickid","irgwc","cid","acid","linkTrack"]},
	{"name":"itch.io","match":"itch.io","flags":"i","rules":["fbclid"]},
	{"name":"microsoft.com","match":"microsoft.com","flags":"i","rules":["refd","icid"]},
	{"name":"berrybase.de","match":"berrybase.de","flags":"i","rules":["sPartner"]},
	{"name":"instagram.com","match":"instagram.com","flags":"i","rules":["igshid","igsh","source"]},
	{"name":"hubspot.com","match":"hubspot.com","flags":"i","rules":["hubs_content-cta","hubs_content"]},
	{"name":"ebay.com","match":"^(?:https?:\\/\\/)?(?:[^.]+\\.)?ebay\\.[a-z0-9]{0,3}","flags":"i","rules":["amdata","var","hash","_trkparms","_trksid","_from","mkcid","mkrid","campid","toolid","mkevt","customid","siteid","ufes_redirect","ff3","pub","media","widget_ver","ssspo","sssrc","ssuid"],"allow":["epid","_nkw"]},
	{"name":"shopee.com","match":"^(?:https?:\\/\\/)?(?:[^.]+\\.)?shopee\\.[a-z0-9]{0,3}","flags":"i","rules":["af_siteid","pid","af_click_lookback","af_viewthrough_lookback","is_retargeting","af_reengagement_window","af_sub_siteid","c"]},
	{"name":"msn.com","match":"www.msn.com","flags":"i","rules":["ocid","cvid","pc"]},
	{"name":"nuuvem.com","match":"www.nuuvem.com","flags":"i","rules":["ranMID","ranEAID","ranSiteID"]},
	{"name":"linksynergy.com","match":".*.linksynergy.com","flags":"i","rules":["id","mid"]},
	{"name":"cnbc.com","match":"www.cnbc.com","flags":"i","rules":["__source"]},
	{"name":"yahoo.com","match":"yahoo.com","flags":"i","rules":["guce_referrer","guce_referrer_sig","guccounter","soc_src","soc_trk","tsrc"]},
	{"name":"techcrunch.com","match":"techcrunch.com","flags":"i","rules":["guce_referrer","guce_referrer_sig","guccounter"]},
	{"name":"office.com","match":"office.com","flags":"i","rules":["from"]},
	{"name":"ticketmaster.co.nz","match":"ticketmaster.co.nz","flags":"i","rules":["tm_link"]},
	{"name":"bostonglobe.com","match":"bostonglobe.com","flags":"i","rules":["p1"]},
	{"name":"ampproject.org","match":"cdn.ampproject.org","flags":"i","rules":["amp_gsa","amp_js_v","usqp","outputType"]},
	{"name":"nbcnews.com","match":"nbcnews.com","flags":"i","rules":["fbclid"]},
	{"name":"countdown.co.nz","match":"www.countdown.co.nz","flags":"i","rules":["promo_name","promo_creative","promo_position","itemID"]},
	{"name":"etsy.com","match":"www.etsy.com","flags":"i","rules":["click_key","click_sum","rec_type","ref","frs","sts","dd_referrer"]},
	{"name":"wattpad.com","match":"www.wattpad.com","flags":"i","rules":["wp_page","wp_uname","wp_originator"]},
	{"name":"noctre.com","match":"www.noctre.com","flags":"i","rules":["aff"]},
	{"name":"dreamgame.com","match":"www.dreamgame.com","flags":"i","rules":["affiliate"]},
	{"name":"startpage.com","match":".*.startpage.com","flags":"i","rules":["source"]},
	{"name":"2game.com","match":"^2game.com","flags":"i","rules":["ref"]},
	{"name":"gamesplanet.com","match":"^(?:.*\\.|)gamesplanet\\.com","flags":"i","rules":["ref"]},
	{"name":"gamersgate.com","match":"www.gamersgate.com","flags":"i","rules":["aff"]},
	{"name":"ranker.com","match":"^(www|blog).ranker.com","flags":"i","rules":["ref","rlf","l","li_source","li_medium"]},
	{"name":"watchworthy.app","match":"^watchworthy.app","flags":"i","rules":["ref"]},
	{"name":"squarespace.com","match":"^.*.squarespace.com","flags":"i","rules":["subchannel","source","subcampaign","campaign","channel","_ga"]},
	{"name":"baidu.com","match":"^www.baidu.com","flags":"i","rules":["rsv_spt","rsv_idx","rsv_pq","rsv_t","rsv_bp","rsv_dl","rsv_iqid","rsv_enter","rsv_sug1","rsv_sug2","rsv_sug3","rsv_sug4","rsv_sug5","rsv_sug6","rsv_sug7","rsv_sug8","rsv_sug9","rsv_sug7","rsv_btype","tn","sa","rsf","rqid","usm","__pc2ps_ab","p_signature","p_sign","p_timestamp","p_tk","oq"],"allow":["wd","ie"]},
	{"name":"primevideo.com","match":"^www.primevideo.com","flags":"i","rules":["dclid"]},
	{"name":"threadless.com","match":"^www.threadless.com","flags":"i","rules":["itm_source_s","itm_medium_s","itm_campaign_s"]},
	{"name":"wsj.com","match":"^www.wsj.com","flags":"i","rules":["mod"]},
	{"name":"thewarehouse.co.nz","match":"^www.thewarehouse.co.nz","flags":"i","rules":["sfmc_j","sfmc_id","sfmc_mid","sfmc_uid","sfmc_id","sfmc_activityid"]},
	{"name":"ko-fi.com","match":"^ko-fi.com","flags":"i","rules":["ref","src"]},
	{"name":"indiegala.com","match":"^www.indiegala.com","flags":"i","rules":["ref"]},
	{"name":"transparency.fb.com","match":"^transparency.fb.com","flags":"i","rules":["source"]},
	{"name":"manymorestores.com","match":"^www.manymorestores.com","flags":"i","rules":["ref"]},
	{"name":"macgamestore.com","match":"^www.macgamestore.com","flags":"i","rules":["ars"]},
	{"name":"blizzardgearstore.com","match":"^www.blizzardgearstore.com","flags":"i","rules":["_s"]},
	{"name":"playbook.com","match":"^www.playbook.com","flags":"i","rules":["p"]},
	{"name":"cookiepro.com","match":"^.*.cookiepro.com","flags":"i","rules":["source","referral"]},
	{"name":"pinterest.com","match":"^www\\.pinterest\\..*","flags":"i","rules":["rs"]},
	{"name":"bing.com","match":"^www\\.bing\\.com","flags":"i","rules":["qs","form","sp","pq","sc","sk","cvid","FORM","ck","simid","thid","cdnurl","pivotparams","ghsh","ghacc","ccid","","ru"],"allow":["q","tsc","iss","id","view","setlang"]},
	{"name":"jf79.net","match":"^jf79\\.net","flags":"i","rules":["li","wi","ws","ws2"]},
	{"name":"frankenergie.nl","match":"^www\\.frankenergie\\.nl","flags":"i","rules":["aff_id"]},
	{"name":"nova.cz","match":"^.*\\.nova\\.cz","flags":"i","rules":["sznclid"]},
	{"name":"cnn.com","match":".*.cnn.com","flags":"i","rules":["hpt","iid"],"exclude":[{"match":"e.newsletters.cnn.com","flags":"i"}]},
	{"name":"justwatch.com","match":"click\\.justwatch\\.com","flags":"i","rules":["cx","uct_country","uct_buybox","sid"]},
	{"name":"psychologytoday.com","match":"www\\.psychologytoday\\.com","flags":"i","rules":["amp"]},
	{"name":"mouser.com","match":"www\\.mouser\\.com","flags":"i","rules":["qs"]},
	{"name":"awin1.com","match":"www\\.awin1\\.com","flags":"i","rules":["awinmid","awinaffid","clickref"]},
	{"name":"castorama.fr","match":"www\\.castorama\\.fr","flags":"i","rules":["syte_ref"]},
	{"name":"quizlet.com","match":"quizlet\\.com","flags":"i","rules":["funnelUUID","source"]},
	{"name":"pbtech.co.nz","match":"www\\.pbtech\\.co\\.nz","flags":"i","rules":["qr"]},
	{"name":"matomo.org","match":"matomo\\.org","flags":"i","rules":["menu","footer","header","hp-reasons-learn","hp-top","above-fold","step1-hp","mid-hp","take-back-control-hp","hp-reasons-icon","hp-reasons-heading","hp-reasons-p","hp-bottom","footer","menu"]},
	{"name":"eufy.com","match":"eufy\\.com","flags":"i","rules":["ref"]},
	{"name":"newsflare.com","match":"www\\.newsflare\\.com","flags":"i","rules":["jwsource"]},
	{"name":"wish.com","match":"www\\.wish\\.com","flags":"i","rules":["share"]},
	{"name":"change.org","match":"www\\.change\\.org","flags":"i","rules":["source_location"]},
	{"name":"washingtonpost.com","match":".*\\.washingtonpost\\.com","flags":"i","rules":["itid","s_l"]},
	{"name":"lowes.com","match":"www\\.lowes\\.com","flags":"i","rules":["cm_mmc","ds_rl","gbraid"]},
	{"name":"stacks.wellcomecollection.org","match":"stacks\\.wellcomecollection\\.org","flags":"i","rules":["source"]},
	{"name":"redbubble.com","match":".*\\.redbubble\\.com","flags":"i","rules":["ref"]},
	{"name":"inyourarea.co.uk","match":"inyourarea.co.uk","flags":"i","rules":["from_reach_primary_nav","from_reach_footer_nav","branding"]},
	{"name":"fiverr.com","match":".*\\.fiverr\\.com","flags":"i","rules":["source","context_referrer","referrer_gig_slug","ref_ctx_id","funnel","imp_id"]},
	{"name":"kqzyfj.com","match":"www\\.kqzyfj\\.com","flags":"i","rules":["cjsku","pubdata"]},
	{"name":"marca.com","match":".*\\.marca\\.com","flags":"i","rules":["intcmp","s_kw","emk"]},
	{"name":"marcaentradas.com","match":".*\\.marcaentradas\\.com","flags":"i","rules":["intcmp","s_kw"]},
	{"name":"honeycode.aws","match":".*\\.honeycode\\.aws","flags":"i","rules":["trackingId","sc_icampaign","sc_icontent","sc_ichannel","sc_iplace","sc_country","sc_outcome","sc_geo","sc_campaign","sc_channel","trkCampaign","trk"]},
	{"name":"studentbeans.com","match":"www\\.studentbeans\\.com","flags":"i","rules":["source"]},
	{"name":"boxofficemojo.com","match":"boxofficemojo.com","flags":"i","rules":["ref_"]},
	{"name":"solodeportes.com.ar","match":"www.solodeportes.com.ar","flags":"i","rules":["nosto","refSrc"]},
	{"name":"joybuggy.com","match":"joybuggy.com","flags":"i","rules":["ref"]},
	{"name":"etail.market","match":"etail.market","flags":"i","rules":["tracking"]},
	{"name":"myanimelist.net","match":"myanimelist.net","flags":"i","rules":["_location","click_type","click_param"]},
	{"name":"support-dev.discord.com","match":"support-dev.discord.com","flags":"i","rules":["ref"]},
	{"name":"dlgamer.com","match":"dlgamer.com","flags":"i","rules":["affil"]},
	{"name":"newsletter.manor.ch","match":"newsletter.manor.ch","flags":"i","rules":["user_id_1"]},
	{"name":"producthunt.com","match":"producthunt.com","flags":"i","rules":["ref"]},
	{"name":"cbsnews.com","match":"www.cbsnews.com","flags":"i","rules":["ftag","intcid"]},
	{"name":"jobs.venturebeat.com","match":"jobs.venturebeat.com","flags":"i","rules":["source"]},
	{"name":"wfaa.com","match":"www.wfaa.com","flags":"i","rules":["ref"]},
	{"name":"buyatoyota.com","match":"www.buyatoyota.com","flags":"i","rules":["siteid"]},
	{"name":"independent.co.uk","match":"www.independent.co.uk","flags":"i","rules":["amp","regSourceMethod"]},
	{"name":"cooking.nytimes.com","match":"cooking.nytimes.com","flags":"i","rules":["smid","variant","algo","req_id","surface","imp_id","action","region","module","pgType"]},
	{"name":"optigruen.com","match":"www\\.optigruen\\.[a-z0-9]{0,3}","flags":"i","rules":["cHash","chash","mdrv"]},
	{"name":"osi.rosenberger.com","match":"osi.rosenberger.com","flags":"i","rules":["cHash","chash"]},
	{"name":"cbc.ca","match":"cbc.ca","flags":"i","rules":["__vfz","cmp","referrer"]},
	{"name":"local12.com","match":"local12.com","flags":"i","rules":["_gl"]},
	{"name":"eufylife.com","match":"eufylife.com","flags":"i","rules":["ref"]},
	{"name":"walmart.com","match":"walmart.com","flags":"i","rules":["athAsset","povid","wmlspartner","athcpid","athpgid","athznid","athmtid","athstid","athguid","athwpid","athtvid","athcgid","athieid","athancid","athbdg","campaign_id","eventST","bt","pos","rdf","tax","plmt","mloc","pltfm","pgId","pt","spQs","adUid","adsRedirect"]},
	{"name":"dyno.gg","match":"dyno.gg","flags":"i","rules":["ref"]},
	{"name":"eufylife.com","match":"eufylife.com","flags":"i","rules":["ref"]},
	{"name":"connect.studentbeans.com","match":"connect.studentbeans.com","flags":"i","rules":["ref"]},
	{"name":"s.pemsrv.com","match":"s.pemsrv.com","flags":"i","rules":["cat","idzone","type","sub","block","el","tags","cookieconsent","scr_info"]},
	{"name":"chess.com","match":"www.chess.com","flags":"i","rules":["c"]},
	{"name":"porndude.link","match":"porndude.link","flags":"i","rules":["ref"]},
	{"name":"xvideos.com","match":"xvideos.com","flags":"i","rules":["sxcaf"]},
	{"name":"xvideos.red","match":"xvideos.red","flags":"i","rules":["sxcaf","pmsc","pmln"]},
	{"name":"xhamster.com","match":"xhamster.com","flags":"i","rules":["source"]},
	{"name":"milkrun.com","match":"milkrun.com","flags":"i","rules":["_branch_match_id","_branch_referrer"]},
	{"name":"gog.salesmanago.com","match":"gog.salesmanago.com","flags":"i","rules":["smclient","smconv","smlid"]},
	{"name":"dailymail.co.uk","match":"dailymail.co.uk","flags":"i","rules":["reg_source","ito"]},
	{"name":"hashnode.com","match":"(?:.*\\.)?hashnode\\.com","flags":"i","rules":["source"]},
	{"name":"s.amazon-adsystem.com","match":"s.amazon-adsystem.com","flags":"i","rules":["dsig","d","ex-fch","ex-fargs","cb"]},
	{"name":"theguardian.com","match":"theguardian.com","flags":"i","rules":["INTCMP","acquisitionData","REFPVID"]},
	{"name":"seek.co.nz","match":"www.seek.co.nz","flags":"i","rules":["tracking","sc_trk"]},
	{"name":"seekvolunteer.co.nz","match":"seekvolunteer.co.nz","flags":"i","rules":["tracking","sc_trk"]},
	{"name":"seekbusiness.com.au","match":"www.seekbusiness.com.au","flags":"i","rules":["tracking","cid"]},
	{"name":"garageclothing.com","match":"www.garageclothing.com","flags":"i","rules":["syte_ref","site_ref"]},
	{"name":"urbandictionary.com","match":"urbandictionary.com","flags":"i","rules":["amp"]},
	{"name":"norml.org","match":"norml.org","flags":"i","rules":["amp"]},
	{"name":"nbcconnecticut.com","match":"www.nbcconnecticut.com","flags":"i","rules":["amp"]},
	{"name":"ladysmithchronicle.com","match":"www.ladysmithchronicle.com","flags":"i","rules":["ref"]},
	{"name":"m10news.com","match":"m10news.com","flags":"i","rules":["amp"]},
	{"name":"libretro.com","match":"www.libretro.com","flags":"i","rules":["amp"]},
	{"name":"bostonherald.com","match":"bostonherald.com","flags":"i","rules":["g2i_source","g2i_medium","g2i_campaign"]},
	{"name":"playshoptitans.com","match":"playshoptitans.com","flags":"i","rules":["af_ad","pid","source_caller","shortlink","c"]},
	{"name":"news.com.au","match":"www.news.com.au","flags":"i","rules":["sourceCode"]},
	{"name":"wvva.com","match":"www.wvva.com","flags":"i","rules":["outputType"]},
	{"name":"realestate.com.au","match":"www.realestate.com.au","flags":"i","rules":["campaignType","campaignChannel","campaignName","campaignContent","campaignSource","campaignPlacement","sourcePage","sourceElement","cid"]},
	{"name":"redirectingat.com","match":"redirectingat.com","flags":"i","rules":["id","xcust","xs"]},
	{"name":"map.sewoon.org","match":"map.sewoon.org","flags":"i","rules":["cid"]},
	{"name":"vi-control.net","match":"[&?]source=https:\\/\\/vi-control\\.net\\/community$","flags":"","matchHref":true,"rules":["source"]},
	{"name":"rosequake.com","match":"www.rosequake.com","flags":"i","rules":["edmID","linkID","userID","em","taskItemID"]},
	{"name":"rekrute.com","match":"www.rekrute.com","flags":"i","rules":["clear"]},
	{"name":"go.skimresources.com","match":"go.skimresources.com","flags":"i","rules":["id","xs","xcust"]},
	{"name":"khnum-ezi.com","match":"khnum-ezi.com","flags":"i","rules":["browserWidth","browserHeight","iframeDetected","webdriverDetected","gpu","timezone","visitid","type","timezoneName"]},
	{"name":"theatlantic.com","match":"(?:www|accounts)\\.theatlantic\\.com","flags":"i","rules":["source","referral"]},
	{"name":"rumble.com","match":"rumble.com","flags":"i","rules":["e9s"]},
	{"name":"cointiply.com","match":"cointiply.com","flags":"i","rules":["source_cta"]},
	{"name":"dev.to","match":"dev.to","flags":"","rules":["t","s","u"]},
	{"name":"milda-clq.com","match":"milda-clq.com","flags":"","rules":["visitid","type","browserWidth","browserHeight","webdriverDetected","timezone","gpu","iframeDetected","timezoneName"]},
	{"name":"app.message.asce","match":".*.app\\.message\\.asce\\.org","flags":"i","rules":[],"allow":["elq"]},
];
